name: Deploy action

on:
  push:
    branches: [none] # [main, beta, alpha]
  workflow_dispatch: # allow manually deploying from Actions tab

jobs:
  deploy-git-tag-and-release:
    name: Deploy git tags
    runs-on: ubuntu-latest
    permissions:
      contents: write # push git commits/releases 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run compile 

      - name: Deploy via semantic release 
        uses: cycjimmy/semantic-release-action@v4
        with: 
          extra_plugins: |
            conventional-changelog-conventionalcommits@6.1.0 
            @semantic-release/git
            @semantic-release/github
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  major-version-bump:
    runs-on: ubuntu-latest
    needs: deploy-git-tag-and-release # to wait for new git tag to be made. 
    permissions:
      contents: write # so it can push a tag
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: npm ci
    - run: npm run compile 
    - uses: ./