name: Test

on: [pull_request]

jobs:
  test:
    name: Run tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci  
      - run: npm run test
      
  test-can-compile:
    name: Test can compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci  
      - run: npm run compile 